<a href="https://colab.research.google.com/github/sonu-raut-dev/GenAI-Learning/blob/main/DataPreprocessing/Text_Representation_Word_Embedding_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Bag of words

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({"text": [
        "The cat sat on the mat",                # 1
        "The dog barked at the cat",             # 0
        "The cat chased the mouse",              # 0
        "A dog chased a ball in the park",       # 0
        "The mouse ran under the table",         # 0
        "Dogs and cats can be friends",          # 1
        "The park was full of people and dogs",  # 1
        "A ball rolled across the street",       # 0
        "Cats like to sleep on warm mats",       # 1
        "The dog and the cat played together"    # 1
    ],
    "output": [1, 0, 0, 0, 0, 1, 1, 0, 1, 1]  })

df

text  output
0                The cat sat on the mat       1
1             The dog barked at the cat       0
2              The cat chased the mouse       0
3       A dog chased a ball in the park       0
4         The mouse ran under the table       0
5          Dogs and cats can be friends       1
6  The park was full of people and dogs       1
7       A ball rolled across the street       0
8       Cats like to sleep on warm mats       1
9   The dog and the cat played together       1

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df["text"])

In [6]:
#vocabulary
print(cv.vocabulary_)

{'the': 30, 'cat': 7, 'sat': 26, 'on': 20, 'mat': 16, 'dog': 10, 'barked': 4, 'at': 2, 'chased': 9, 'mouse': 18, 'ball': 3, 'in': 14, 'park': 21, 'ran': 24, 'under': 33, 'table': 29, 'dogs': 11, 'and': 1, 'cats': 8, 'can': 6, 'be': 5, 'friends': 12, 'was': 35, 'full': 13, 'of': 19, 'people': 22, 'rolled': 25, 'across': 0, 'street': 28, 'like': 15, 'to': 31, 'sleep': 27, 'warm': 34, 'mats': 17, 'played': 23, 'together': 32}


In [7]:
bow.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],


In [8]:
 cv.transform(['Dogs like the ball']).toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [9]:
x = bow.toarray()
y = df["output"]

#now think this we will pass to model

## N-grams

In [10]:
df = pd.DataFrame({"text": [
        "The cat sat on the mat",                # 1
        "The dog barked at the cat",             # 0
        "The cat chased the mouse",              # 0
        "A dog chased a ball in the park",       # 0
        "The mouse ran under the table",         # 0
        "Dogs and cats can be friends",          # 1
        "The park was full of people and dogs",  # 1
        "A ball rolled across the street",       # 0
        "Cats like to sleep on warm mats",       # 1
        "The dog and the cat played together"    # 1
    ],
    "output": [1, 0, 0, 0, 0, 1, 1, 0, 1, 1]  })

In [11]:
#bi-gram , and with 3 word Ti-gram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [12]:
bow = cv.fit_transform(df['text'])

In [13]:
print(cv.vocabulary_)

{'the cat': 35, 'cat sat': 12, 'sat on': 33, 'on the': 26, 'the mat': 37, 'the dog': 36, 'dog barked': 18, 'barked at': 7, 'at the': 4, 'cat chased': 10, 'chased the': 16, 'the mouse': 38, 'dog chased': 19, 'chased ball': 15, 'ball in': 5, 'in the': 22, 'the park': 39, 'mouse ran': 24, 'ran under': 31, 'under the': 43, 'the table': 41, 'dogs and': 20, 'and cats': 1, 'cats can': 13, 'can be': 9, 'be friends': 8, 'park was': 28, 'was full': 45, 'full of': 21, 'of people': 25, 'people and': 29, 'and dogs': 2, 'ball rolled': 6, 'rolled across': 32, 'across the': 0, 'the street': 40, 'cats like': 14, 'like to': 23, 'to sleep': 42, 'sleep on': 34, 'on warm': 27, 'warm mats': 44, 'dog and': 17, 'and the': 3, 'cat played': 11, 'played together': 30}


## TF-IDF (Term frequency-Inverse document frequescy)

In [14]:
df = pd.DataFrame({"text": [
        "The cat sat on the mat",                # 1
        "The dog barked at the cat",             # 0
        "The cat chased the mouse",              # 0
        "A dog chased a ball in the park",       # 0
        "The mouse ran under the table",         # 0
        "Dogs and cats can be friends",          # 1
        "The park was full of people and dogs",  # 1
        "A ball rolled across the street",       # 0
        "Cats like to sleep on warm mats",       # 1
        "The dog and the cat played together"    # 1
    ],
    "output": [1, 0, 0, 0, 0, 1, 1, 0, 1, 1]  })

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()
# it uses a formula to get the value , you can search on web

In [16]:
arr = tfid.fit_transform(df['text']).toarray()

In [17]:
arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.3327799 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.50327496, 0.        , 0.        , 0.        ,
        0.42782969, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.50327496, 0.        , 0.        , 0.        ,
        0.44681979, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.51444051, 0.        , 0.51444051,
        0.        , 0.        , 0.34016288, 0.        , 0.        ,
        0.38260457, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.45673284, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
      

In [18]:
print(tfid.idf_)

[2.70474809 2.01160091 2.70474809 2.29928298 2.70474809 2.70474809
 2.70474809 1.78845736 2.29928298 2.29928298 2.01160091 2.29928298
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.29928298 2.70474809 2.29928298 2.29928298 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 1.2006707  2.70474809 2.70474809 2.70474809 2.70474809 2.70474809]
